"""
ADAPTIVE-DMS

Real-Time Monitoring Dashboard

Version:
    v1.6

Features:
    - Memory-safe CSV loading
    - Live processed camera frame
    - System status
    - Camera status
    - Session duration
    - Alert count
    - Manual refresh
    - Fatigue risk
    - Risk level
    - EAR
    - MAR
    - PERCLOS
    - Eye closure duration
    - Gaze direction
    - Head pose
    - Signal reliability
    - Safety intervention
    - Live graphs
    - Event and Alert Timeline
    - Event Statistics
"""

import os
import glob
import csv
import time

import pandas as pd
import streamlit as st
import plotly.graph_objects as go


# =============================================================
# CONFIGURATION
# =============================================================

MAX_ROWS = 1500

MAX_EVENTS = 300

LIVE_FRAME_PATH = os.path.join(
    "logs",
    "live_frame.jpg",
)

EVENT_FILE_PATH = os.path.join(
    "logs",
    "events.csv",
)

LIVE_FRAME_TIMEOUT = 5.0


# =============================================================
# PAGE CONFIGURATION
# =============================================================

st.set_page_config(
    page_title="ADAPTIVE-DMS",
    page_icon="🚗",
    layout="wide",
    initial_sidebar_state="expanded",
)


# =============================================================
# CUSTOM CSS
# =============================================================

st.markdown(
    """
    <style>

    .main-title {
        font-size: 42px;
        font-weight: 800;
        margin-bottom: 0px;
    }

    .sub-title {
        font-size: 17px;
        opacity: 0.75;
        margin-bottom: 20px;
    }

    .status-card {
        padding: 18px;
        border-radius: 12px;
        border: 1px solid rgba(128,128,128,0.25);
        min-height: 115px;
    }

    .alert-banner {
        padding: 15px;
        border-radius: 12px;
        text-align: center;
        font-size: 20px;
        font-weight: 700;
        margin: 10px 0 20px 0;
    }

    .alert-safe {
        background: rgba(0, 200, 83, 0.12);
        border: 1px solid rgba(0, 200, 83, 0.35);
    }

    .alert-warning {
        background: rgba(255, 152, 0, 0.16);
        border: 1px solid rgba(255, 152, 0, 0.40);
    }

    .alert-danger {
        background: rgba(244, 67, 54, 0.18);
        border: 1px solid rgba(244, 67, 54, 0.45);
    }

    </style>
    """,
    unsafe_allow_html=True,
)


# =============================================================
# SIDEBAR
# =============================================================

with st.sidebar:

    st.header(
        "⚙️ Dashboard Controls"
    )

    if st.button(
        "🔄 Refresh Now",
        use_container_width=True,
    ):

        st.cache_data.clear()

        st.rerun()

    st.divider()

    st.subheader(
        "System"
    )

    st.write(
        "Version: **v1.6**"
    )

    st.write(
        "Camera owner: **main.py**"
    )

    st.write(
        "Dashboard mode: **Read-only**"
    )

    st.divider()

    st.caption(
        "The dashboard does not open camera 0. "
        "It reads the processed frame generated by main.py."
    )


# =============================================================
# HEADER
# =============================================================

st.markdown(
    '<div class="main-title">'
    '🚗 ADAPTIVE-DMS'
    '</div>',
    unsafe_allow_html=True,
)

st.markdown(
    '<div class="sub-title">'
    'Adaptive Multimodal Driver State Monitoring '
    'and Predictive Safety Intervention System'
    '</div>',
    unsafe_allow_html=True,
)


# =============================================================
# HELPER FUNCTIONS
# =============================================================

def find_latest_session():

    files = glob.glob(
        os.path.join(
            "logs",
            "session_*.csv",
        )
    )

    if not files:

        return None

    return max(
        files,
        key=os.path.getmtime,
    )


def safe_float(
    value,
    default=0.0,
):

    try:

        if pd.isna(value):

            return default

        return float(value)

    except Exception:

        return default


def safe_text(
    value,
    default="UNKNOWN",
):

    try:

        if pd.isna(value):

            return default

        return str(value)

    except Exception:

        return default


def get_file_age(
    file_path
):

    try:

        modified = os.path.getmtime(
            file_path
        )

        return (
            time.time()
            - modified
        )

    except Exception:

        return float("inf")


def is_live_frame_active():

    if not os.path.exists(
        LIVE_FRAME_PATH
    ):

        return False

    age = get_file_age(
        LIVE_FRAME_PATH
    )

    return age <= LIVE_FRAME_TIMEOUT


# =============================================================
# MEMORY-SAFE SESSION CSV LOADER
# =============================================================

@st.cache_data(ttl=2)
def load_recent_data(
    file_path,
    file_modified_time,
):

    try:

        if not os.path.exists(
            file_path
        ):

            return pd.DataFrame()

        file_size = os.path.getsize(
            file_path
        )

        if file_size <= 0:

            return pd.DataFrame()

        # -----------------------------------------------------
        # Read header
        # -----------------------------------------------------

        with open(
            file_path,
            "r",
            encoding="utf-8",
            errors="ignore",
            newline="",
        ) as file:

            header_line = file.readline()

        if not header_line:

            return pd.DataFrame()

        header_line = header_line.strip()

        if not header_line:

            return pd.DataFrame()

        # -----------------------------------------------------
        # Read last 512 KB only
        # -----------------------------------------------------

        max_bytes = 512 * 1024

        bytes_to_read = min(
            file_size,
            max_bytes,
        )

        with open(
            file_path,
            "rb",
        ) as file:

            file.seek(
                -bytes_to_read,
                os.SEEK_END,
            )

            raw_data = file.read()

        text = raw_data.decode(
            "utf-8",
            errors="ignore",
        )

        lines = text.splitlines()

        if len(lines) < 2:

            return pd.DataFrame()

        data_lines = lines[1:]

        if not data_lines:

            return pd.DataFrame()

        # -----------------------------------------------------
        # Keep latest rows
        # -----------------------------------------------------

        if len(data_lines) > MAX_ROWS:

            data_lines = data_lines[
                -MAX_ROWS:
            ]

        # -----------------------------------------------------
        # Header
        # -----------------------------------------------------

        header_reader = csv.reader(
            [header_line]
        )

        headers = next(
            header_reader
        )

        if not headers:

            return pd.DataFrame()

        header_length = len(
            headers
        )

        # -----------------------------------------------------
        # Parse rows
        # -----------------------------------------------------

        reader = csv.reader(
            data_lines
        )

        valid_rows = []

        for row in reader:

            if not row:

                continue

            if len(row) < 5:

                continue

            if len(row) == header_length:

                valid_rows.append(
                    row
                )

            elif len(row) > header_length:

                valid_rows.append(
                    row[
                        :header_length
                    ]
                )

            else:

                padded_row = (
                    row
                    + [""] * (
                        header_length
                        - len(row)
                    )
                )

                valid_rows.append(
                    padded_row
                )

        if not valid_rows:

            return pd.DataFrame()

        df = pd.DataFrame(
            valid_rows,
            columns=headers,
        )

        if df.empty:

            return df

        # -----------------------------------------------------
        # Timestamp
        # -----------------------------------------------------

        if "timestamp" not in df.columns:

            return pd.DataFrame()

        df["timestamp"] = pd.to_datetime(
            df["timestamp"],
            errors="coerce",
        )

        df = df.dropna(
            subset=[
                "timestamp"
            ]
        )

        if df.empty:

            return df

        # -----------------------------------------------------
        # Numeric columns
        # -----------------------------------------------------

        numeric_columns = [

            "ear",
            "mar",
            "perclos",
            "blink_count",
            "blink_duration",
            "microsleep_duration",
            "pitch",
            "yaw",
            "roll",
            "gaze_away_duration",
            "reliability",
            "fatigue_risk",
            "eye_closure_duration",
        ]

        for column in numeric_columns:

            if column in df.columns:

                df[column] = pd.to_numeric(
                    df[column],
                    errors="coerce",
                )

        # -----------------------------------------------------
        # Boolean columns
        # -----------------------------------------------------

        boolean_columns = [

            "eyes_closed",
            "microsleep",
            "alert_triggered",
        ]

        for column in boolean_columns:

            if column in df.columns:

                df[column] = (
                    df[column]
                    .astype(str)
                    .str.strip()
                    .str.lower()
                    .map(
                        {
                            "true": 1,
                            "false": 0,
                            "1": 1,
                            "0": 0,
                        }
                    )
                    .fillna(0)
                )

        # -----------------------------------------------------
        # Elapsed seconds
        # -----------------------------------------------------

        df["elapsed_seconds"] = (
            df["timestamp"]
            - df["timestamp"].iloc[0]
        ).dt.total_seconds()

        return df

    except (
        OSError,
        PermissionError,
        MemoryError,
        UnicodeError,
        csv.Error,
    ):

        return pd.DataFrame()


# =============================================================
# EVENT CSV LOADER
# =============================================================

@st.cache_data(ttl=2)
def load_events(
    file_path,
    file_modified_time,
):

    try:

        if not os.path.exists(
            file_path
        ):

            return pd.DataFrame(
                columns=[
                    "timestamp",
                    "event_type",
                    "severity",
                    "message",
                ]
            )

        file_size = os.path.getsize(
            file_path
        )

        if file_size <= 0:

            return pd.DataFrame(
                columns=[
                    "timestamp",
                    "event_type",
                    "severity",
                    "message",
                ]
            )

        # -----------------------------------------------------
        # Read only a limited amount of event data
        # -----------------------------------------------------

        max_bytes = 256 * 1024

        bytes_to_read = min(
            file_size,
            max_bytes,
        )

        with open(
            file_path,
            "rb",
        ) as file:

            file.seek(
                -bytes_to_read,
                os.SEEK_END,
            )

            raw_data = file.read()

        text = raw_data.decode(
            "utf-8",
            errors="ignore",
        )

        lines = text.splitlines()

        if not lines:

            return pd.DataFrame()

        # -----------------------------------------------------
        # Find header
        # -----------------------------------------------------

        header = (
            "timestamp,event_type,severity,message"
        )

        header_index = -1

        for index, line in enumerate(
            lines
        ):

            if line.strip() == header:

                header_index = index

                break

        if header_index >= 0:

            data_lines = lines[
                header_index + 1:
            ]

        else:

            data_lines = lines

        if not data_lines:

            return pd.DataFrame(
                columns=[
                    "timestamp",
                    "event_type",
                    "severity",
                    "message",
                ]
            )

        # -----------------------------------------------------
        # Limit events
        # -----------------------------------------------------

        if len(data_lines) > MAX_EVENTS:

            data_lines = data_lines[
                -MAX_EVENTS:
            ]

        reader = csv.reader(
            data_lines
        )

        rows = []

        for row in reader:

            if len(row) < 4:

                continue

            rows.append(
                [
                    row[0],
                    row[1],
                    row[2],
                    ",".join(
                        row[3:]
                    ),
                ]
            )

        if not rows:

            return pd.DataFrame()

        df = pd.DataFrame(
            rows,
            columns=[
                "timestamp",
                "event_type",
                "severity",
                "message",
            ],
        )

        # -----------------------------------------------------
        # Convert timestamp
        # -----------------------------------------------------

        df["timestamp"] = pd.to_datetime(
            df["timestamp"],
            errors="coerce",
        )

        df = df.dropna(
            subset=[
                "timestamp"
            ]
        )

        # -----------------------------------------------------
        # Sort newest first
        # -----------------------------------------------------

        df = df.sort_values(
            "timestamp",
            ascending=False,
        )

        return df.reset_index(
            drop=True
        )

    except (
        OSError,
        PermissionError,
        MemoryError,
        UnicodeError,
        csv.Error,
    ):

        return pd.DataFrame()


# =============================================================
# FIND SESSION
# =============================================================

session_file = find_latest_session()


# =============================================================
# SYSTEM STATUS
# =============================================================

camera_active = is_live_frame_active()

session_active = (
    session_file is not None
)

if camera_active and session_active:

    system_status = "RUNNING"

elif session_active:

    system_status = "SESSION AVAILABLE"

elif camera_active:

    system_status = "CAMERA ACTIVE"

else:

    system_status = "WAITING"


# =============================================================
# TOP HEADER
# =============================================================

st.subheader(
    "📡 System Status"
)

status_col1, status_col2, status_col3, status_col4 = st.columns(
    4
)


with status_col1:

    if system_status == "RUNNING":

        st.success(
            "🟢 SYSTEM RUNNING"
        )

    elif system_status == "WAITING":

        st.warning(
            "🟡 WAITING"
        )

    else:

        st.info(
            f"ℹ️ {system_status}"
        )


with status_col2:

    if camera_active:

        st.success(
            "🎥 CAMERA ACTIVE"
        )

    else:

        st.error(
            "🔴 CAMERA OFFLINE"
        )


with status_col3:

    if session_active:

        st.success(
            "📝 SESSION AVAILABLE"
        )

    else:

        st.warning(
            "📝 NO SESSION"
        )


with status_col4:

    current_time = time.strftime(
        "%H:%M:%S"
    )

    st.metric(
        "Dashboard Time",
        current_time,
    )


# =============================================================
# NO SESSION
# =============================================================

if session_file is None:

    st.divider()

    st.warning(
        "No session CSV found."
    )

    st.info(
        "Start main.py and wait for the "
        "session logger to create a session."
    )

    st.stop()


# =============================================================
# SESSION FILE TIME
# =============================================================

try:

    file_modified_time = os.path.getmtime(
        session_file
    )

except Exception:

    file_modified_time = time.time()


# =============================================================
# LOAD SESSION DATA
# =============================================================

df = load_recent_data(
    session_file,
    file_modified_time,
)


if df.empty:

    st.divider()

    st.warning(
        "Waiting for readable session data..."
    )

    st.info(
        "Keep main.py running and wait a few seconds."
    )

    time.sleep(2)

    st.rerun()


# =============================================================
# LOAD EVENTS
# =============================================================

if os.path.exists(
    EVENT_FILE_PATH
):

    try:

        event_modified_time = os.path.getmtime(
            EVENT_FILE_PATH
        )

    except Exception:

        event_modified_time = time.time()

else:

    event_modified_time = time.time()


events_df = load_events(
    EVENT_FILE_PATH,
    event_modified_time,
)


# =============================================================
# LATEST SESSION DATA
# =============================================================

latest = df.iloc[-1]


# =============================================================
# CURRENT VALUES
# =============================================================

fatigue_risk = safe_float(
    latest.get(
        "fatigue_risk",
        0.0,
    )
)

ear = safe_float(
    latest.get(
        "ear",
        0.0,
    )
)

mar = safe_float(
    latest.get(
        "mar",
        0.0,
    )
)

perclos = safe_float(
    latest.get(
        "perclos",
        0.0,
    )
)

reliability = safe_float(
    latest.get(
        "reliability",
        0.0,
    )
)

eye_closure_duration = safe_float(
    latest.get(
        "eye_closure_duration",
        0.0,
    )
)

pitch = safe_float(
    latest.get(
        "pitch",
        0.0,
    )
)

yaw = safe_float(
    latest.get(
        "yaw",
        0.0,
    )
)

roll = safe_float(
    latest.get(
        "roll",
        0.0,
    )
)


# =============================================================
# TEXT VALUES
# =============================================================

risk_level = safe_text(
    latest.get(
        "risk_level",
        "UNKNOWN",
    )
).upper()

temporal_state = safe_text(
    latest.get(
        "temporal_state",
        "UNKNOWN",
    )
)

intervention_level = safe_text(
    latest.get(
        "intervention_level",
        "UNKNOWN",
    )
)

intervention_action = safe_text(
    latest.get(
        "intervention_action",
        "UNKNOWN",
    )
)

gaze_direction = safe_text(
    latest.get(
        "gaze_direction",
        "UNKNOWN",
    )
)


# =============================================================
# SESSION ALERT COUNT
# =============================================================

if "alert_triggered" in df.columns:

    session_alert_count = int(
        pd.to_numeric(
            df[
                "alert_triggered"
            ],
            errors="coerce",
        )
        .fillna(0)
        .sum()
    )

else:

    session_alert_count = 0


# =============================================================
# EVENT COUNTS
# =============================================================

if events_df.empty:

    total_events = 0

    eye_closure_events = 0

    microsleep_events = 0

    yawning_events = 0

    gaze_away_events = 0

    risk_transition_events = 0

    intervention_events = 0

else:

    total_events = len(
        events_df
    )

    eye_closure_events = int(
        (
            events_df[
                "event_type"
            ]
            == "EYE_CLOSURE"
        ).sum()
    )

    microsleep_events = int(
        (
            events_df[
                "event_type"
            ]
            == "MICROSLEEP"
        ).sum()
    )

    yawning_events = int(
        (
            events_df[
                "event_type"
            ]
            == "YAWNING"
        ).sum()
    )

    gaze_away_events = int(
        (
            events_df[
                "event_type"
            ]
            == "GAZE_AWAY"
        ).sum()
    )

    risk_transition_events = int(
        (
            events_df[
                "event_type"
            ]
            == "RISK_TRANSITION"
        ).sum()
    )

    intervention_events = int(
        (
            events_df[
                "event_type"
            ]
            == "INTERVENTION"
        ).sum()
    )


# =============================================================
# RISK BANNER
# =============================================================

if risk_level in (
    "HIGH",
    "CRITICAL",
):

    alert_class = "alert-danger"

    alert_text = (
        "🚨 HIGH RISK — "
        "DRIVER ATTENTION REQUIRED"
    )

elif risk_level == "MODERATE":

    alert_class = "alert-warning"

    alert_text = (
        "⚠️ MODERATE RISK — "
        "MONITOR DRIVER STATE"
    )

elif risk_level == "LOW":

    alert_class = "alert-warning"

    alert_text = (
        "🟡 LOW RISK — "
        "DRIVER CONDITION REQUIRES MONITORING"
    )

else:

    alert_class = "alert-safe"

    alert_text = (
        "🟢 DRIVER STATE STABLE"
    )


st.markdown(
    f'<div class="alert-banner '
    f'{alert_class}">'
    f'{alert_text}'
    f'</div>',
    unsafe_allow_html=True,
)


# =============================================================
# SESSION OVERVIEW
# =============================================================

st.subheader(
    "📊 Session Overview"
)

c1, c2, c3, c4 = st.columns(
    4
)


if "elapsed_seconds" in df.columns:

    session_duration = safe_float(
        df[
            "elapsed_seconds"
        ].iloc[-1]
    )

else:

    session_duration = 0.0


session_minutes = int(
    session_duration // 60
)

session_seconds = int(
    session_duration % 60
)


with c1:

    st.metric(
        "⏱️ Session Duration",
        (
            f"{session_minutes:02d}:"
            f"{session_seconds:02d}"
        ),
    )


with c2:

    st.metric(
        "🚨 Alerts",
        session_alert_count,
    )


with c3:

    st.metric(
        "📊 Events",
        total_events,
    )


with c4:

    st.metric(
        "🎯 Fatigue Risk",
        f"{fatigue_risk:.2f}",
    )


# =============================================================
# LIVE CAMERA
# =============================================================

st.divider()

st.subheader(
    "🎥 Live Camera Monitoring"
)

if os.path.exists(
    LIVE_FRAME_PATH
):

    try:

        with open(
            LIVE_FRAME_PATH,
            "rb",
        ) as image_file:

            live_frame = image_file.read()

        if live_frame:

            st.image(
                live_frame,
                caption=(
                    "Processed live camera feed"
                ),
                use_container_width=True,
            )

            frame_age = get_file_age(
                LIVE_FRAME_PATH
            )

            if frame_age <= LIVE_FRAME_TIMEOUT:

                st.success(
                    f"🟢 Live feed active "
                    f"({frame_age:.1f}s ago)"
                )

            else:

                st.warning(
                    f"⚠️ Live feed appears stale "
                    f"({frame_age:.1f}s old)"
                )

        else:

            st.warning(
                "Camera frame is empty."
            )

    except Exception as error:

        st.error(
            f"Unable to read live frame: {error}"
        )

else:

    st.info(
        "Waiting for main.py to generate "
        "the live camera frame..."
    )


# =============================================================
# CURRENT RISK
# =============================================================

st.divider()

left, right = st.columns(
    [1, 2]
)


with left:

    st.subheader(
        "🎯 Current Risk"
    )

    st.metric(
        "Risk Level",
        risk_level,
    )

    st.metric(
        "Fatigue Risk",
        f"{fatigue_risk:.2f}",
    )

    if risk_level in (
        "HIGH",
        "CRITICAL",
    ):

        st.error(
            "🚨 Driver attention required"
        )

    elif risk_level == "MODERATE":

        st.warning(
            "⚠️ Moderate fatigue risk"
        )

    elif risk_level == "LOW":

        st.warning(
            "🟡 Low fatigue risk"
        )

    else:

        st.success(
            "🟢 Driver state normal"
        )


with right:

    c1, c2, c3, c4 = st.columns(
        4
    )

    with c1:

        st.metric(
            "👁️ EAR",
            f"{ear:.3f}",
        )

    with c2:

        st.metric(
            "📊 PERCLOS",
            f"{perclos:.3f}",
        )

    with c3:

        st.metric(
            "😮 MAR",
            f"{mar:.3f}",
        )

    with c4:

        st.metric(
            "🚨 Alerts",
            session_alert_count,
        )


# =============================================================
# DRIVER MONITORING STATUS
# =============================================================

st.divider()

st.subheader(
    "🧠 Driver Monitoring Status"
)

c1, c2, c3, c4 = st.columns(
    4
)


with c1:

    st.markdown(
        f"""
        <div class="status-card">
        <b>Temporal State</b>
        <br><br>
        {temporal_state}
        </div>
        """,
        unsafe_allow_html=True,
    )


with c2:

    st.markdown(
        f"""
        <div class="status-card">
        <b>Intervention</b>
        <br><br>
        {intervention_level}
        </div>
        """,
        unsafe_allow_html=True,
    )


with c3:

    st.markdown(
        f"""
        <div class="status-card">
        <b>Gaze Direction</b>
        <br><br>
        👀 {gaze_direction}
        </div>
        """,
        unsafe_allow_html=True,
    )


with c4:

    st.markdown(
        f"""
        <div class="status-card">
        <b>Signal Reliability</b>
        <br><br>
        📡 {reliability:.2f}
        </div>
        """,
        unsafe_allow_html=True,
    )


# =============================================================
# EYE CLOSURE
# =============================================================

st.subheader(
    "👁️ Eye Closure Monitoring"
)

eye_col1, eye_col2 = st.columns(
    2
)


with eye_col1:

    st.metric(
        "Current Eye Closure",
        f"{eye_closure_duration:.2f} sec",
    )


with eye_col2:

    if eye_closure_duration >= 1.5:

        st.error(
            "🚨 Eye closure threshold reached"
        )

    elif eye_closure_duration > 0:

        st.warning(
            "⚠️ Eyes currently closed"
        )

    else:

        st.success(
            "🟢 Eyes open"
        )


# =============================================================
# EVENT STATISTICS
# =============================================================

st.divider()

st.subheader(
    "📊 Event Statistics"
)

e1, e2, e3, e4, e5, e6 = st.columns(
    6
)


with e1:

    st.metric(
        "👁️ Eye Closure",
        eye_closure_events,
    )


with e2:

    st.metric(
        "😴 Microsleep",
        microsleep_events,
    )


with e3:

    st.metric(
        "😮 Yawning",
        yawning_events,
    )


with e4:

    st.metric(
        "👀 Gaze Away",
        gaze_away_events,
    )


with e5:

    st.metric(
        "⚠️ Risk Changes",
        risk_transition_events,
    )


with e6:

    st.metric(
        "🔔 Interventions",
        intervention_events,
    )


# =============================================================
# EVENT TIMELINE
# =============================================================

st.divider()

st.subheader(
    "🚨 Event & Alert Timeline"
)

if events_df.empty:

    st.info(
        "No events recorded yet."
    )

    st.caption(
        "Events will appear here when "
        "eye closure, microsleep, yawning, "
        "gaze-away, risk transitions, or "
        "interventions are detected."
    )

else:

    # ---------------------------------------------------------
    # Timeline chart
    # ---------------------------------------------------------

    timeline_df = events_df.copy()

    timeline_df[
        "event_number"
    ] = range(
        len(timeline_df),
        0,
        -1,
    )

    event_type_numbers = {
        "EYE_CLOSURE": 1,
        "MICROSLEEP": 2,
        "YAWNING": 3,
        "GAZE_AWAY": 4,
        "RISK_TRANSITION": 5,
        "INTERVENTION": 6,
    }

    timeline_df[
        "event_y"
    ] = (
        timeline_df[
            "event_type"
        ]
        .map(
            event_type_numbers
        )
        .fillna(7)
    )

    fig_events = go.Figure()

    fig_events.add_trace(
        go.Scatter(
            x=timeline_df[
                "timestamp"
            ],
            y=timeline_df[
                "event_y"
            ],
            mode="markers",
            text=timeline_df[
                "event_type"
            ],
            customdata=timeline_df[
                [
                    "severity",
                    "message",
                ]
            ],
            hovertemplate=(
                "<b>%{text}</b><br>"
                "Time: %{x}<br>"
                "Severity: %{customdata[0]}<br>"
                "%{customdata[1]}"
                "<extra></extra>"
            ),
            marker=dict(
                size=12,
            ),
            name="Events",
        )
    )

    fig_events.update_yaxes(
        tickmode="array",
        tickvals=[
            1,
            2,
            3,
            4,
            5,
            6,
        ],
        ticktext=[
            "Eye Closure",
            "Microsleep",
            "Yawning",
            "Gaze Away",
            "Risk Transition",
            "Intervention",
        ],
    )

    fig_events.update_layout(
        xaxis_title="Timestamp",
        yaxis_title="Event Type",
        height=420,
        showlegend=False,
    )

    st.plotly_chart(
        fig_events,
        use_container_width=True,
    )

    # ---------------------------------------------------------
    # Event table
    # ---------------------------------------------------------

    st.subheader(
        "📋 Recent Events"
    )

    display_events = events_df[
        [
            "timestamp",
            "event_type",
            "severity",
            "message",
        ]
    ].copy()

    display_events[
        "timestamp"
    ] = display_events[
        "timestamp"
    ].dt.strftime(
        "%Y-%m-%d %H:%M:%S"
    )

    st.dataframe(
        display_events,
        use_container_width=True,
        hide_index=True,
    )


# =============================================================
# FATIGUE RISK GRAPH
# =============================================================

st.divider()

st.subheader(
    "📈 Live Fatigue Risk"
)

if "fatigue_risk" in df.columns:

    fig_risk = go.Figure()

    fig_risk.add_trace(
        go.Scatter(
            x=df[
                "elapsed_seconds"
            ],
            y=df[
                "fatigue_risk"
            ],
            mode="lines",
            name="Fatigue Risk",
            line=dict(
                width=3
            ),
        )
    )

    for threshold, label in [
        (0.20, "Low"),
        (0.35, "Moderate"),
        (0.55, "High"),
        (0.75, "Critical"),
    ]:

        fig_risk.add_hline(
            y=threshold,
            line_dash="dash",
            annotation_text=label,
        )

    fig_risk.update_layout(
        xaxis_title="Time (seconds)",
        yaxis_title="Fatigue Risk",
        yaxis_range=[
            0,
            1,
        ],
        height=420,
    )

    st.plotly_chart(
        fig_risk,
        use_container_width=True,
    )


# =============================================================
# EAR + PERCLOS
# =============================================================

c1, c2 = st.columns(
    2
)


with c1:

    st.subheader(
        "👁️ Eye Aspect Ratio"
    )

    if "ear" in df.columns:

        fig_ear = go.Figure()

        fig_ear.add_trace(
            go.Scatter(
                x=df[
                    "elapsed_seconds"
                ],
                y=df[
                    "ear"
                ],
                mode="lines",
                name="EAR",
            )
        )

        fig_ear.add_hline(
            y=0.21,
            line_dash="dash",
            annotation_text="EAR Threshold",
        )

        fig_ear.update_layout(
            xaxis_title="Time (seconds)",
            yaxis_title="EAR",
            height=350,
        )

        st.plotly_chart(
            fig_ear,
            use_container_width=True,
        )


with c2:

    st.subheader(
        "📊 PERCLOS"
    )

    if "perclos" in df.columns:

        fig_perclos = go.Figure()

        fig_perclos.add_trace(
            go.Scatter(
                x=df[
                    "elapsed_seconds"
                ],
                y=df[
                    "perclos"
                ],
                mode="lines",
                name="PERCLOS",
            )
        )

        fig_perclos.update_layout(
            xaxis_title="Time (seconds)",
            yaxis_title="PERCLOS",
            height=350,
        )

        st.plotly_chart(
            fig_perclos,
            use_container_width=True,
        )


# =============================================================
# HEAD POSE
# =============================================================

st.subheader(
    "🧭 Head Pose"
)

fig_pose = go.Figure()


if "pitch" in df.columns:

    fig_pose.add_trace(
        go.Scatter(
            x=df[
                "elapsed_seconds"
            ],
            y=df[
                "pitch"
            ],
            mode="lines",
            name="Pitch",
        )
    )


if "yaw" in df.columns:

    fig_pose.add_trace(
        go.Scatter(
            x=df[
                "elapsed_seconds"
            ],
            y=df[
                "yaw"
            ],
            mode="lines",
            name="Yaw",
        )
    )


if "roll" in df.columns:

    fig_pose.add_trace(
        go.Scatter(
            x=df[
                "elapsed_seconds"
            ],
            y=df[
                "roll"
            ],
            mode="lines",
            name="Roll",
        )
    )


fig_pose.update_layout(
    xaxis_title="Time (seconds)",
    yaxis_title="Angle (degrees)",
    height=400,
)

st.plotly_chart(
    fig_pose,
    use_container_width=True,
)


# =============================================================
# SIGNAL RELIABILITY
# =============================================================

st.subheader(
    "📡 Signal Reliability"
)

if "reliability" in df.columns:

    fig_reliability = go.Figure()

    fig_reliability.add_trace(
        go.Scatter(
            x=df[
                "elapsed_seconds"
            ],
            y=df[
                "reliability"
            ],
            mode="lines",
            name="Reliability",
        )
    )

    fig_reliability.update_layout(
        xaxis_title="Time (seconds)",
        yaxis_title="Reliability",
        yaxis_range=[
            0,
            1,
        ],
        height=350,
    )

    st.plotly_chart(
        fig_reliability,
        use_container_width=True,
    )


# =============================================================
# SAFETY INTERVENTION
# =============================================================

st.divider()

st.subheader(
    "🚨 Safety Intervention"
)

c1, c2, c3 = st.columns(
    3
)


with c1:

    st.metric(
        "Intervention Level",
        intervention_level,
    )


with c2:

    st.metric(
        "Action",
        intervention_action,
    )


with c3:

    st.metric(
        "Total Alerts",
        session_alert_count,
    )


# =============================================================
# CURRENT HEAD POSE
# =============================================================

st.subheader(
    "🧭 Current Head Pose"
)

c1, c2, c3 = st.columns(
    3
)


with c1:

    st.metric(
        "Pitch",
        f"{pitch:.1f}°",
    )


with c2:

    st.metric(
        "Yaw",
        f"{yaw:.1f}°",
    )


with c3:

    st.metric(
        "Roll",
        f"{roll:.1f}°",
    )


# =============================================================
# SESSION INFORMATION
# =============================================================

st.divider()

st.subheader(
    "📋 Session Information"
)

c1, c2, c3 = st.columns(
    3
)


with c1:

    st.write(
        "**Session:**"
    )

    st.code(
        os.path.basename(
            session_file
        )
    )


with c2:

    st.write(
        "**Session duration:**"
    )

    st.write(
        (
            f"{session_minutes:02d}:"
            f"{session_seconds:02d}"
        )
    )


with c3:

    st.write(
        "**Displayed samples:**"
    )

    st.write(
        len(df)
    )


# =============================================================
# DATA HEALTH
# =============================================================

st.divider()

st.subheader(
    "🔍 Data Health"
)

csv_age = get_file_age(
    session_file
)

frame_age = get_file_age(
    LIVE_FRAME_PATH
)

event_age = get_file_age(
    EVENT_FILE_PATH
)

c1, c2, c3 = st.columns(
    3
)


with c1:

    if csv_age <= 5:

        st.success(
            f"🟢 Session data fresh "
            f"({csv_age:.1f}s)"
        )

    else:

        st.warning(
            f"🟡 Session data stale "
            f"({csv_age:.1f}s)"
        )


with c2:

    if frame_age <= LIVE_FRAME_TIMEOUT:

        st.success(
            f"🟢 Camera frame fresh "
            f"({frame_age:.1f}s)"
        )

    else:

        st.warning(
            f"🟡 Camera frame stale "
            f"({frame_age:.1f}s)"
        )


with c3:

    if (
        os.path.exists(
            EVENT_FILE_PATH
        )
        and event_age <= 5
    ):

        st.success(
            f"🟢 Event log active "
            f"({event_age:.1f}s)"
        )

    elif os.path.exists(
        EVENT_FILE_PATH
    ):

        st.warning(
            f"🟡 Event log stale "
            f"({event_age:.1f}s)"
        )

    else:

        st.info(
            "ℹ️ No event log yet"
        )


# =============================================================
# FOOTER
# =============================================================

st.divider()

st.caption(
    "ADAPTIVE-DMS v1.6 | "
    "Real-Time Driver Monitoring + Event Timeline"
)

st.caption(
    "Camera and processing are controlled by main.py."
)

st.caption(
    "Dashboard is read-only and does not access camera 0."
)


# =============================================================
# AUTO REFRESH
# =============================================================

time.sleep(2)

st.rerun()